type PrefecturePrefix = 'Tokyo_';
type PrefectureName =
  | 'Adachi'
  | 'Akiruno'
  | 'Akishima'
  | 'Arakawa'
  | 'Bunkyo'
  | 'Chiyoda'
  | 'Chofu'
  | 'Chuo'
  | 'Edogawa'
  | 'Fuchu'
  | 'Fussa'
  | 'Hachijo'
  | 'Hachioji'
  | 'Hamura'
  | 'Higashikurume'
  | 'Higashimurayama'
  | 'Higashiyamato'
  | 'Hino'
  | 'Hinode'
  | 'Inagi'
  | 'Itabashi'
  | 'Katsushika'
  | 'Kita'
  | 'Kiyose'
  | 'Kodaira'
  | 'Koganei'
  | 'Kokubunji'
  | 'Komae'
  | 'Koto'
  | 'Kunitachi'
  | 'Machida'
  | 'Meguro'
  | 'Minato'
  | 'Mitaka'
  | 'Mizuho'
  | 'Musashimurayama'
  | 'Musashino'
  | 'Nakano'
  | 'NDL'
  | 'Nerima'
  | 'Niijima'
  | 'Nishitokyo'
  | 'Okutama'
  | 'Ome'
  | 'Ota'
  | 'Koganei'
  | 'Setagaya'
  | 'Shibuya'
  | 'Shinagawa'
  | 'Shinjuku'
  | 'Suginami'
  | 'Sumida'
  | 'Tachikawa'
  | 'Taito'
  | 'Tama'
  | 'Toshima';
export type Prefecture = `${PrefecturePrefix}${PrefectureName}`;

export const PrefectureList: [Prefecture, string][] = [
  ['Tokyo_Adachi', '足立区'],
  ['Tokyo_Akiruno', 'あきる野市'],
  ['Tokyo_Akishima', '昭島市'],
  ['Tokyo_Arakawa', '荒川区'],
  ['Tokyo_Bunkyo', '文京区'],
  ['Tokyo_Chiyoda', '千代田区'],
  ['Tokyo_Chofu', '調布市'],
  ['Tokyo_Chuo', '中央区'],
  ['Tokyo_Edogawa', '江戸川区'],
  ['Tokyo_Fuchu', '府中市'],
  ['Tokyo_Fussa', '福生市'],
  ['Tokyo_Hachijo', '八丈町'],
  ['Tokyo_Hachioji', '八王子市'],
  ['Tokyo_Hamura', '羽村市'],
  ['Tokyo_Higashikurume', '東久留米市'],
  ['Tokyo_Higashimurayama', '東村山市'],
  ['Tokyo_Higashiyamato', '東大和市'],
  ['Tokyo_Hino', '日野市'],
  ['Tokyo_Hinode', '日の出町'],
  ['Tokyo_Inagi', '稲城市'],
  ['Tokyo_Itabashi', '板橋区'],
  ['Tokyo_Katsushika', '葛飾区'],
  ['Tokyo_Kita', '北区'],
  ['Tokyo_Kiyose', '清瀬市'],
  ['Tokyo_Kodaira', '小平市'],
  ['Tokyo_Koganei', '小金井市'],
  ['Tokyo_Kokubunji', '国分寺市'],
  ['Tokyo_Komae', '狛江市'],
  ['Tokyo_Koto', '江東区'],
  ['Tokyo_Kunitachi', '国立市'],
  ['Tokyo_Machida', '町田市'],
  ['Tokyo_Meguro', '目黒区'],
  ['Tokyo_Minato', '港区'],
  ['Tokyo_Mitaka', '三鷹市'],
  ['Tokyo_Mizuho', '瑞穂町'],
  ['Tokyo_Musashimurayama', '武蔵村山市'],
  ['Tokyo_Musashino', '武蔵野市'],
  ['Tokyo_Nakano', '中野区'],
  ['Tokyo_NDL', '国立国会図書館'],
  ['Tokyo_Nerima', '練馬区'],
  ['Tokyo_Niijima', '新島村'],
  ['Tokyo_Nishitokyo', '西東京市'],
  ['Tokyo_Okutama', '奥多摩町'],
  ['Tokyo_Ome', '青梅市'],
  ['Tokyo_Ota', '大田区'],
  ['Tokyo_Setagaya', '世田谷区'],
  ['Tokyo_Shibuya', '渋谷区'],
  ['Tokyo_Shinagawa', '品川区'],
  ['Tokyo_Shinjuku', '新宿区'],
  ['Tokyo_Suginami', '杉並区'],
  ['Tokyo_Sumida', '墨田区'],
  ['Tokyo_Tachikawa', '立川市'],
  ['Tokyo_Taito', '台東区'],
  ['Tokyo_Tama', '多摩市'],
  ['Tokyo_Toshima', '豊島区']
];
